context:
  name: pyearthviz3d
  version: "0.1.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/changliao1025/pyearthviz3d/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 8157e225cfdae449736bfb37537e4c390d2d9ea33f63e3f0d7a0acd3f39d76f8

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python >=${{ python_min }}
    - numpy
    - geovista
    - pyvista
    - gdal >=3.0.0
    - pyearth >=0.2.2

tests:
  - python:
      imports:
        - pyearthviz3d
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/changliao1025/pyearthviz3d
  summary: '3D visualization for Earth science data'
  description: |
    PyEarthViz3d is a lightweight Python package for 3D visualization of Earth science data.
  license: BSD-3-Clause
  license_file: LICENSE
  documentation: https://pyearthviz3d.readthedocs.io/
  repository: https://github.com/changliao1025/pyearthviz3d

extra:
  recipe-maintainers:
    - changliao1025
