context:
  name: pyearthviz3d
  version: "0.1.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/changliao1025/pyearthviz3d/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 4e839c507aed73e48bd5051e95bc2599f55a58d8127b5c635a1befeb754de5a6

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=61.0
    - wheel
    - pyearth >=0.2.2
  run:
    - python >=${{ python_min }}
    - numpy
    - geovista
    - pyvista
    - gdal >=3.0.0
    - pyearth >=0.2.2

tests:
  - python:
      imports:
        - pyearthviz3d
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/changliao1025/pyearthviz3d
  summary: '3D visualization for geospatial and Earth science data'
  description: |
    pyearthviz3d is a lightweight Python package for 3D visualization and plotting of geospatial and Earth science data.
  license: BSD-3-Clause
  license_file: LICENSE
  documentation: https://pyearthviz3d.readthedocs.io/
  repository: https://github.com/changliao1025/pyearthviz3d

extra:
  recipe-maintainers:
    - changliao1025
